export const DEFAULT_UNIVERSITY_MODULES = [
  {
    order: 0,
    badge: "Módulo 0",
    title: "Bienvenido a SIFRAH",
    theme: "sunset",
    banner: "",
    hideBannerText: false,
    lead: "Tu punto de partida en esta gran oportunidad.",
    active: true,
    files: [
      { name: "Guía de bienvenida", meta: "PDF · 4.2 MB", url: "" },
      { name: "Hoja de trabajo – Mis primeros pasos", meta: "PDF · 1.8 MB", url: "" },
    ],
    videos: [
      {
        id: "m0-v1",
        title: "Gracias por tomar esta decisión",
        duration: "10:25",
        videoUrl: "",
        thumbnail: "",
        theme: "sunset",
        status: "done",
        desc: "Un mensaje de bienvenida, la visión de SIFRAH y lo que puedes lograr.",
        order: 0
      },
      {
        id: "m0-v2",
        title: "Tu punto de partida",
        duration: "08:40",
        videoUrl: "",
        thumbnail: "",
        theme: "notes",
        status: "next",
        desc: "Qué hacer ahora, primeros pasos y recomendaciones.",
        order: 1
      },
      {
        id: "m0-v3",
        title: "Cómo aprovechar la Universidad SIFRAH",
        duration: "06:15",
        videoUrl: "",
        thumbnail: "",
        theme: "laptop",
        status: "pending",
        desc: "Cómo utilizar la plataforma, navegar los módulos y sacar el máximo provecho.",
        order: 2
      },
      {
        id: "m0-v4",
        title: "Tu camino en SIFRAH",
        duration: "07:20",
        videoUrl: "",
        thumbnail: "",
        theme: "portrait",
        status: "pending",
        desc: "Lo que viene, mentalidad, disciplina y próximos pasos.",
        order: 3
      },
    ],
  },
  {
    order: 1,
    badge: "Módulo 1",
    title: "Conoce la industria",
    theme: "city",
    banner: "",
    hideBannerText: false,
    lead: "Entiende el negocio antes de dar el siguiente paso.",
    active: true,
    files: [{ name: "Guía de la industria", meta: "PDF · 2.4 MB", url: "" }],
    videos: [
      { id: "m1-v1", title: "Qué es el Network Marketing", duration: "12:30", videoUrl: "", thumbnail: "", theme: "people", desc: "Introducción a los conceptos clave del Network Marketing.", order: 0 },
      { id: "m1-v2", title: "Mitos y realidades", duration: "09:20", videoUrl: "", thumbnail: "", theme: "climb", desc: "Aclarando las dudas más comunes y realidades del sector.", order: 1 },
      { id: "m1-v3", title: "Oportunidades del mercado", duration: "11:05", videoUrl: "", thumbnail: "", theme: "market", desc: "El potencial de crecimiento en el mercado actual.", order: 2 },
      { id: "m1-v4", title: "Historia de la industria", duration: "08:30", videoUrl: "", thumbnail: "", theme: "history", desc: "De dónde venimos y hacia dónde va la industria.", order: 3 },
      { id: "m1-v5", title: "El camino de la industria", duration: "07:45", videoUrl: "", thumbnail: "", theme: "city", desc: "Tendencias y oportunidades futuras.", order: 4 },
    ],
  },
  {
    order: 2,
    badge: "Módulo 2",
    title: "Conoce SIFRAH",
    theme: "products",
    banner: "",
    hideBannerText: false,
    lead: "La propuesta, los productos y la comunidad.",
    active: true,
    files: [{ name: "Presentación SIFRAH", meta: "PDF · 3.1 MB", url: "" }],
    videos: [
      { id: "m2-v1", title: "Qué es SIFRAH", duration: "09:10", videoUrl: "", thumbnail: "", theme: "products", desc: "Nuestra identidad y valores fundamentales.", order: 0 },
      { id: "m2-v2", title: "La propuesta de valor", duration: "08:05", videoUrl: "", thumbnail: "", theme: "products", desc: "Qué nos hace únicos en el mercado.", order: 1 },
      { id: "m2-v3", title: "Productos principales", duration: "11:20", videoUrl: "", thumbnail: "", theme: "products", desc: "Detalle de nuestra línea de productos y beneficios.", order: 2 },
      { id: "m2-v4", title: "La comunidad", duration: "07:35", videoUrl: "", thumbnail: "", theme: "people", desc: "El poder del trabajo en equipo y la red.", order: 3 },
      { id: "m2-v5", title: "Cómo se crece en SIFRAH", duration: "10:00", videoUrl: "", thumbnail: "", theme: "chart", desc: "Rutas de ascenso y proyección.", order: 4 },
      { id: "m2-v6", title: "Tu siguiente paso", duration: "06:40", videoUrl: "", thumbnail: "", theme: "handshake", desc: "Acciones concretas para seguir avanzando.", order: 5 },
    ],
  },
  {
    order: 3,
    badge: "Módulo 3",
    title: "Plan de compensación",
    theme: "chart",
    banner: "",
    hideBannerText: false,
    lead: "Aprende cómo funciona el plan y cómo maximizarlo.",
    active: true,
    files: [{ name: "Guía del Plan de Compensación", meta: "PDF · 5.0 MB", url: "" }],
    videos: [
      { id: "m3-v1", title: "Introducción al plan", duration: "10:15", videoUrl: "", thumbnail: "", theme: "chart", desc: "Estructura general del plan de compensación.", order: 0 },
      { id: "m3-v2", title: "Cómo funciona el residual", duration: "14:20", videoUrl: "", thumbnail: "", theme: "chart", desc: "Cálculo y potencia del ingreso residual unilevel.", order: 1 },
      { id: "m3-v3", title: "Bonos principales", duration: "11:45", videoUrl: "", thumbnail: "", theme: "chart", desc: "Bonos de patrocinio, liderazgo y otros incentivos.", order: 2 },
      { id: "m3-v4", title: "Estructura de equipo", duration: "09:30", videoUrl: "", thumbnail: "", theme: "people", desc: "Cómo organizar tu red para maximizar rangos.", order: 3 },
      { id: "m3-v5", title: "Rangos y metas", duration: "13:10", videoUrl: "", thumbnail: "", theme: "climb", desc: "Requisitos de cada rango y cómo planificar su alcance.", order: 4 },
      { id: "m3-v6", title: "Estrategias de crecimiento", duration: "12:00", videoUrl: "", thumbnail: "", theme: "chart", desc: "Estrategias efectivas para duplicar el equipo.", order: 5 },
      { id: "m3-v7", title: "Preguntas frecuentes", duration: "08:50", videoUrl: "", thumbnail: "", theme: "notes", desc: "Respuestas a inquietudes habituales sobre el plan.", order: 6 },
      { id: "m3-v8", title: "Plan de acción", duration: "07:30", videoUrl: "", thumbnail: "", theme: "handshake", desc: "Puesta en práctica de lo aprendido.", order: 7 },
    ],
  },
  {
    order: 4,
    badge: "Módulo 4",
    title: "Activación y primeros pasos",
    theme: "handshake",
    banner: "",
    hideBannerText: false,
    lead: "Pasa a la acción con pasos claros y medibles.",
    active: true,
    files: [{ name: "Checklist de activación", meta: "PDF · 1.2 MB", url: "" }],
    videos: [
      { id: "m4-v1", title: "Por qué activarse", duration: "08:15", videoUrl: "", thumbnail: "", theme: "handshake", desc: "La importancia de mantenerse activo mes a mes.", order: 0 },
      { id: "m4-v2", title: "Tus primeras 48 horas", duration: "11:00", videoUrl: "", thumbnail: "", theme: "notes", desc: "Las tareas críticas para arrancar con fuerza.", order: 1 },
      { id: "m4-v3", title: "Tu lista de contactos", duration: "10:30", videoUrl: "", thumbnail: "", theme: "people", desc: "Cómo elaborar y clasificar tu lista de prospectos.", order: 2 },
      { id: "m4-v4", title: "Cómo invitar", duration: "12:15", videoUrl: "", thumbnail: "", theme: "chat", desc: "Guiones y posturas para invitar con éxito.", order: 3 },
      { id: "m4-v5", title: "La primera presentación", duration: "09:45", videoUrl: "", thumbnail: "", theme: "laptop", desc: "Consejos para presentar la oportunidad efectivamente.", order: 4 },
      { id: "m4-v6", title: "Seguimiento y cierre", duration: "11:20", videoUrl: "", thumbnail: "", theme: "handshake", desc: "El arte del seguimiento y resolución de objeciones.", order: 5 },
    ],
  },
];
